<a href="https://colab.research.google.com/github/wooridle/mlp_lecture/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [134]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)|

SyntaxError: ignored

In [135]:
x_train

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])

In [136]:
|print(x_train.shape)
print(y_train.shape)

SyntaxError: ignored

In [ ]:
|W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

In [137]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))

In [138]:
print(hypothesis) # 예측값인 H(x) 출력

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<MulBackward0>)


In [139]:
class LogisticRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.Linear = nn.Linear(2, 1) # input_dim = 2, output_dim = 1
        self.Sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.Linear(x)
        outputs = self.Sigmoid(x)
        return outputs

# class LogisticRegression(torch.nn.Module):
#      def __init__(self, input_dim, output_dim):
#          super(LogisticRegression, self).__init__()
#          self.linear = torch.nn.Linear(input_dim, output_dim)
#      def forward(self, x):
#          outputs = torch.sigmoid(self.linear(x))
#          return outputs


In [140]:
# hypothesis = torch.sigmoid(x_train.matmul(W) + b)

model = LogisticRegression()

In [141]:
print(model)

LogisticRegression(
  (Linear): Linear(in_features=2, out_features=1, bias=True)
  (Sigmoid): Sigmoid()
)


In [142]:
model(x_train)

tensor([[0.6655],
        [0.7669],
        [0.8857],
        [0.9193],
        [0.9549],
        [0.9780]], grad_fn=<SigmoidBackward0>)

In [143]:
print(hypothesis)
print(y_train)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<MulBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [144]:
losses = -(y_train * torch.log(hypothesis) + 
           (1 - y_train) * torch.log(1 - hypothesis))
print(losses)

tensor([[0.0003],
        [0.0321],
        [0.0398],
        [0.0448],
        [0.0018],
        [0.0003]], grad_fn=<NegBackward0>)


In [145]:
cost = losses.mean()

In [146]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.0198, grad_fn=<BinaryCrossEntropyBackward0>)

In [147]:
# optimizer 설정
# optimizer = optim.SGD([W, b], lr=1)
optimizer = optim.SGD(model.parameters(), lr=1)

In [148]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):


    # hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    # cost = -(y_train * torch.log(hypothesis) + 
    #          (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)


    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/1000 Cost: 0.812183 Accuracy 50.00%
Epoch  100/1000 Cost: 0.137423 Accuracy 100.00%
Epoch  200/1000 Cost: 0.081578 Accuracy 100.00%
Epoch  300/1000 Cost: 0.058372 Accuracy 100.00%
Epoch  400/1000 Cost: 0.045585 Accuracy 100.00%
Epoch  500/1000 Cost: 0.037452 Accuracy 100.00%
Epoch  600/1000 Cost: 0.031810 Accuracy 100.00%
Epoch  700/1000 Cost: 0.027660 Accuracy 100.00%
Epoch  800/1000 Cost: 0.024475 Accuracy 100.00%
Epoch  900/1000 Cost: 0.021953 Accuracy 100.00%
Epoch 1000/1000 Cost: 0.019906 Accuracy 100.00%


In [149]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)


In [150]:
list(model.parameters())

[Parameter containing:
 tensor([[3.2504, 1.5165]], requires_grad=True), Parameter containing:
 tensor([-14.4698], requires_grad=True)]

In [127]:
prediction = model >= torch.FloatTensor([0.5])
print(prediction)

TypeError: ignored

In [98]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [23]:
print(W)
print(b)

tensor([[3.8961],
        [1.8565]], requires_grad=True)
tensor([-17.4290], requires_grad=True)
