<a href="https://colab.research.google.com/github/wooridle/mlp_lecture/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

### 1D with PyTorch


t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

print(t)

print(t.dim())  # rank. 즉, 차원

print(t.shape)  # shape

print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


print(t[0], t[1], t[-1])  # 인덱스로 접근

print(t[2:5], t[4:-1])    # 슬라이싱

print(t[:2], t[3:])       # 슬라이싱

### 2D with PyTorch

In [7]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


print(t.dim())  # rank. 즉, 차원

print(t.size()) # shape

print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.

print(t[:, 1].size()) # ↑ 위의 경우의 크기

print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

### 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요함!!

In [11]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [12]:
print(ft.shape)

torch.Size([2, 2, 3])


### 3차원 텐서에서 2차원 텐서로 변경


print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경

print(ft.view([-1, 3]).shape)

### 3차원 텐서의 크기 변경

print(ft.view([-1, 1, 3]))

print(ft.view([-1, 1, 3]).shape)

### 스퀴즈(Squeeze) - 1인 차원을 제거한다.

ft = torch.FloatTensor([[0], [1], [2]])

print(ft)

print(ft.shape)

print(ft.squeeze())

print(ft.squeeze().shape)

### 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

ft = torch.Tensor([0, 1, 2])

print(ft.shape)

print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.

print(ft.unsqueeze(0).shape)

print(ft.view(1, -1))

print(ft.view(1, -1).shape)

## 타입 캐스팅(Type Casting)

In [20]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


print(lt.float())

bt = torch.ByteTensor([True, False, False, True])

print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


print(bt.long())

print(bt.float())

### 연결하기(concatenate)

x = torch.FloatTensor([[1, 2], [3, 4]])

y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))

print(torch.cat([x, y], dim=1))

### 스택킹(Stacking)

In [27]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

print(torch.stack([x, y, z], dim=1))

### ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기
